name: Serverless CD

on:
  workflow_call:
    inputs:
      serverless-version:
        type: string
        default: 2.72.3
      sls-deploy:
        type: boolean
        default: false
      sls-config-file:
        type: string
        default: "serverless.yaml"
      integration-tests-cmd:
        type: string
          
jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: ["${{inputs.nodejs-version}}"]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: configure aws credentials
      if: ${{ github.event.inputs.aws-role-to-assume != ''  || inputs.aws-role-to-assume != '' }}
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{inputs.nodejs-version}}
        role-session-name: "aws-github-session"
        aws-region: "${{ inputs.aws-region }}"
    
    - run: |
        npm install -g serverless@"${{inputs.serverless-version}}"
        npm install -g serverless-dotenv-plugin

    - run: npm ci
    
    - name: serverless deploy
      if: ${{ github.event.inputs.sls-deploy != ''  || inputs.sls-deploy != '' }}
      run: |
        export AWS_SDK_LOAD_CONFIG=1
        serverless deploy --config "${{ inputs.serverless-config-file }}"
        
    - name: integration tests
      if: ${{ github.event.inputs.integration-tests-cmd != ''  || inputs.integration-tests-cmd != '' }}
      run: |
        npm run "${{ inputs.integration-tests-cmd }}"
